version: "3.9"

services:
  nginx-service:
    container_name: nginx
    image: nginx:1.23.4-alpine
    volumes:
      - ./proxy/default.conf:/etc/nginx/conf.d/default.conf
      - /var/www/share-blog:/var/www/share-blog
    restart: unless-stopped
    depends_on:
      - backend-service
    networks:
      - share-blog-net
    ports:
      - 8080:8080
 
  backend-service:
    container_name: backend-service
    build:
      context: .
      args:
        - DEV=false
    expose:
      - 8081
    restart: unless-stopped
    volumes:
      - ./application/db/blog_db.sqlite3:/application/db/blog_db.sqlite3
      - /var/www/share-blog:/var/www/share-blog
    command: >
      sh -c "echo yes | python manage.py collectstatic --settings=app.config.settings.deploy &&
             python manage.py migrate &&
             /venv/bin/uwsgi --emperor --ini /application/uwsgi.ini"
    networks:
      - share-blog-net

networks:
  share-blog-net:
    driver: bridge
